### ISSUE TITLE
KeyError: 'DB00001' 

### ISSUE THREAD

**Issue by waqarkaleemkhan** [YifanDengWHU/DDIMDL#10]
I am trying to run DRKG_drug_spider.py and it is throwing an error KeyError: DB00001.
What I have done is create a drug table first then run your code it is giving me the below error. Can you please help me with what's wrong I am doing?

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-29-bee47ce871dd> in <module>
     51         transporter=''
     52     #Creat a table named drug first, so that you can use the insert sql code.
---> 53     cur.execute("insert into drug(id,name,interaction,smile,target,enzyme,carrier,transporter)values(?,?,?,?,?,?,?,?)",(drug[0][i],name,interaction,smile,target,enzyme,carrier,transporter))
     54 conn.commit()
     55 conn.close()

~\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
   1066         key = com.apply_if_callable(key, self)
   1067         try:
-> 1068             result = self.index.get_value(self, key)
   1069 
   1070             if not is_scalar(result):

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4728         k = self._convert_scalar_indexer(k, kind="getitem")
   4729         try:
-> 4730             return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
   4731         except KeyError as e1:
   4732             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index_class_helper.pxi in pandas._libs.index.Int64Engine._check_type()

KeyError: 'DB00001'

**Comment by YifanDengWHU** [comment]
Could you please provide your drug table and your code  around
``` 
drug=pd.read_excel("drug_list.xlsx",header=None)
url_id=drug.iloc[:,0]
for i in url_id:
    soup=download(basic_url,i,num_retries=150)
```
It seems that the problem is related to pandas, so I think there may be something to do with your table.

**Comment by waqarkaleemkhan** [comment]
@YifanDengWHU  
This is the code you asked for

basic_url='https://www.drugbank.ca/drugs/'
event=[]
drug=pd.read_excel("drug_list.xlsx",header=None)
url_id=drug.iloc[:,0]
for i in url_id:
    soup=download(basic_url,i,num_retries=150)
    try:
        d_iden=identification(soup)
    except:
        continue
    try:
        name=d_iden['Name']
    except:
        name=''
    try:
        smile=d_iden['SMILES']
        if smile=='Not Available':
            smile=''
    except:
        smile=''
    interaction,event=interactions(i,name)

    d_attr=head_attr(soup)
    try:
        target=d_attr['Targets']
    except:
        target=''
    try:
        enzyme=d_attr['Enzymes']
    except:
        enzyme=''
    try:
        carrier=d_attr['Carriers']
    except:
        carrier=''
    try:
        transporter=d_attr['Transporters']
    except:
        transporter=''
    #Creat a table named drug first, so that you can use the insert sql code.
    cur.execute("insert into drug(id,name,interaction,smile,target,enzyme,carrier,transporter)values(?,?,?,?,?,?,?,?)",(drug[0][i],name,interaction,smile,target,enzyme,carrier,transporter))
conn.commit()
conn.close()

And this is the table I created
![image](https://user-images.githubusercontent.com/37707339/116731762-910b6900-aa03-11eb-9896-74115dc51407.png)

**Comment by YifanDengWHU** [comment]
I found the problem. The drug[0][i] in line 141 should be changed into i. There are quite a lot of versions in my spider program so I misused it in this program. I have fixed it. Thanks for pointing it out!
