### ISSUE TITLE
Smiles Didn't extracted using DRKG_drug_spider.py

### ISSUE THREAD

**Issue by waqarkaleemkhan** [YifanDengWHU/DDIMDL#11]
Hi, @YifanDengWHU hope you will be doing well I run the DRKG_drug_spider.py file It did scrape the fields e.g enzymes, targets, etc but it didn't extract the smiles field from the drug bank databse the smiles field is empty it's not showing any smiles for any of the drug's I am attaching the pic below you can see.

![image](https://user-images.githubusercontent.com/37707339/116915301-44bf6380-ac65-11eb-827e-06657bf70183.png)

**Comment by YifanDengWHU** [comment]
Sorry for the late response. I traveled these two days.
I checked the code and found that it is because of the HTML upgrade in their website. The SMILES went to another place so my spider program didn't catch it. I'm trying to fix it during the following days. Thank you for pointing it out!

**Comment by waqarkaleemkhan** [comment]
Hi, @YifanDengWHU thanks for your response I have run your DDIMDL.py code but the epochs didn't reach 100 it goes to like 27 then start from 1 again then goes for 18 epochs then start from 1 again why the code is behaving like this you can see the results in below pics

![scr1](https://user-images.githubusercontent.com/37707339/117186668-80d4fe80-adf4-11eb-86cb-767c68e2b484.PNG)

![scr2](https://user-images.githubusercontent.com/37707339/117186733-934f3800-adf4-11eb-9328-3b53f6a81bf9.PNG)
![scr3](https://user-images.githubusercontent.com/37707339/117186776-9fd39080-adf4-11eb-9483-7296732e248b.PNG)
![scr4](https://user-images.githubusercontent.com/37707339/117186814-a6620800-adf4-11eb-9830-73f1741d6952.PNG)

**Comment by waqarkaleemkhan** [comment]
And please update the requirements file the DDIMDL code is not working If you have a Tensorflow =>2.0 the TensorFlow version must be <2.0

**Comment by YifanDengWHU** [comment]
Because I used the early stop strategy. 
Yes, the tf 2.0 isn't compatible with my keras version, thanks for your advice!

**Comment by waqarkaleemkhan** [comment]
Thank you so much @YifanDengWHU

**Comment by 00SoCRaT00** [comment]
can you help me please test this model or how i can use
