### ISSUE TITLE
Ask for the DDI types of Devision

### ISSUE THREAD

**Issue by Savant-HO** [YifanDengWHU/DDIMDL#20]

**Comment by Savant-HO** [comment]
老师，您好，我是生物医药学院一名大三的学生，我最近在研究DDI问题，我想问一下，爬下来的event是怎么划分类型的？怎么分成65种的？另外，如果有相关代码给我学习一下，那就最好了！我的邮箱：857843466@qq.com

**Comment by 00SoCRaT00** [comment]
did you get any help !

**Comment by Savant-HO** [comment]
收到啦收到啦～

**Comment by 00SoCRaT00** [comment]
can you help me run this model please ?
